name: Distribute templates

on:
  schedule:
    - cron: '55 1 * * 1'
  workflow_dispatch:

env:
  UPDATE_BRANCH: update-from-template
  REMOTE_BRANCH: master

permissions:
  contents: write
  pull-requests: write

jobs:
  distribute:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        # Base
        - source: base-template
          target: standard-maven-template
        - source: base-template
          target: xdev-swing-framework-template
        # Standard Maven
        - source: standard-maven-template
          target: vaadin-addon-template
        - source: standard-maven-template
          target: openapi-client-maven-template
        
    steps:
      - uses: actions/checkout@v3
        with:
          # Required because otherwise there are always changes detected when executing diff/rev-list
          fetch-depth: 0
          # If no PAT is used the following error occurs on a push:
          # refusing to allow a GitHub App to create or update workflow `.github/workflows/xxx.yml` without `workflows` permission
          token: ${{ secrets.UPDATE_FROM_TEMPLATE_PAT }}
          repository: xdev-software/${{ matrix.target }}
      
      - name: Init Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Main workflow
        id: main
        run: |
          echo "Adding remote template-repo"
          git remote add template https://github.com/xdev-software/${{ matrix.source }}
          
          echo "Fetching remote template repo"
          git fetch template
          
          echo "Deleting local branch that will contain the updates - if present"
          git branch -D ${{ env.UPDATE_BRANCH }} || true
          
          echo "Checking if the remote template repo has new commits"
          git rev-list ..template/${{ env.REMOTE_BRANCH }}

          if [ $(git rev-list --count ..template/${{ env.REMOTE_BRANCH }}) -eq 0 ]; then
            echo "There are no commits new commits on the template repo"
            
            echo "Deleting origin branch that contains the updates - if present"
            git push -f origin --delete ${{ env.UPDATE_BRANCH }} || true
            
            echo "abort=1" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Found new commits on the template repo"
          
          echo "Creating update branch"
          git branch ${{ env.UPDATE_BRANCH }} template/${{ env.REMOTE_BRANCH }}
          git branch --unset-upstream ${{ env.UPDATE_BRANCH }}
          
          echo "Pushing update branch"
          git push -f -u origin ${{ env.UPDATE_BRANCH }}
          
          echo "Getting current branch"
          current_branch=$(git branch --show-current)
          echo "Current branch is $current_branch"
          echo "current_branch=$current_branch" >> $GITHUB_OUTPUT

          echo "abort=0" >> $GITHUB_OUTPUT
          
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: steps.main.outputs.abort == 0
        with:
          destination_repository: xdev-software/${{ matrix.target }}
          github_token: ${{ secrets.UPDATE_FROM_TEMPLATE_PAT }}
          source_branch: ${{ env.UPDATE_BRANCH }}
          destination_branch: ${{ steps.main.outputs.current_branch }}
          pr_title: "Update from template"
          pr_body: "An automated PR to sync changes from the template into this repo"
          
